# The site title
title: "Samplasion"

# Title separator (eg. " - ", outputs in "Page title - Site title")
separator: " - "

# The base url for the repo
baseurl: /blog

# SASS compiler
sass:
  sass_dir: _sass
  style: compact
