# The site title
title: "Samplasion's Blog"

# The site description
description: "My blog with guides, how-tos and personal accomplishments."

# Title separator (eg. " - ", outputs in "Page title - Site title")
separator: " - "

# Blog URL
url: https://blog.samplasion.js.org

# The base url for the repo
baseurl: /

# SASS compiler
sass:
  sass_dir: _sass
  style: compact

# Default values
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" #but the type must be posts
    values:
      layout: "post"
      comments: true
  -
    scope:
      path: ""
    values:
      socials: true

# Additional plugins
plugins: 
  - jekyll-paginate
  - jemoji
  - jekyll-coffeescript
  - jekyll-sitemap

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Author
author:
  url: https://samplasion.js.org
  name: Samplasion
  links:
    - title: Twitter
      url: https://twitter.com/Samplasion

# Hide scheduled posts
future: false

# Set post permalink
permalink: /:title

# Tags
tags:
  - Apple
  - Samplasion
  - Blog
  - Technology
  - Web
  - PC
  - Linux